===== ZEVORA_BUNDLE_PATH: web/src/components/AdminPanel.tsx =====
import React,{useEffect,useState} from 'react';
import {ArrowRight, Users, Video, Flag, ShieldCheck, RefreshCw, LogIn} from 'lucide-react';

type Overview={usersTotal:number;videosTotal:number;videosPublic:number;reportsPending:number;reportsTotal:number;sessionsActive:number;sessionsTotal:number};
export const AdminPanel:React.FC<{onBack:()=>void}> = ({onBack})=>{
 const [key,setKey]=useState(''); const [authorized,setAuthorized]=useState(false); const [data,setData]=useState<Overview|null>(null); const [reports,setReports]=useState<any[]>([]); const [users,setUsers]=useState<any[]>([]); const [error,setError]=useState('');
 const load=async()=>{setError('');try{const h={Authorization:`Bearer ${key}`};const [o,r,u]=await Promise.all([fetch('/api/v1/admin/overview',{headers:h}),fetch('/api/v1/admin/reports',{headers:h}),fetch('/api/v1/admin/users',{headers:h})]);if(!o.ok||!r.ok||!u.ok) throw new Error(`رفض الخادم الوصول (${o.status}/${r.status})`);setData(await o.json());const rd=await r.json();setReports(rd.items||[]); const ud=await u.json(); setUsers(ud.items||[]);setAuthorized(true);}catch(e:any){setAuthorized(false);setError(e.message||'تعذر الاتصال بلوحة الإدارة');}};
 useEffect(()=>{const t=localStorage.getItem('zevora_admin_token');if(t){setKey(t);}},[]);
 if(!authorized)return <div className="fixed inset-0 z-[90] bg-zinc-950 text-white flex items-center justify-center p-5" dir="rtl"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.04] p-6"><button onClick={onBack} className="mb-6"><ArrowRight/></button><h1 className="text-2xl font-black">لوحة ZEVORA الإدارية</h1><p className="text-xs text-zinc-500 mt-2">استخدم جلسة JWT لحساب إداري حقيقي. لا توجد أرقام تجريبية.</p><input value={key} onChange={e=>setKey(e.target.value)} placeholder="Bearer token" className="mt-5 w-full rounded-xl bg-black border border-white/10 p-3 text-xs" dir="ltr"/><button onClick={()=>{localStorage.setItem('zevora_admin_token',key);load()}} className="mt-3 w-full rounded-xl py-3 bg-gradient-to-r from-fuchsia-600 to-cyan-500 font-bold flex items-center justify-center gap-2"><LogIn className="w-4 h-4"/> دخول</button>{error&&<p className="text-xs text-red-400 mt-3">{error}</p>}</div></div>;
 return <div className="fixed inset-0 z-[90] bg-zinc-950 text-white overflow-y-auto" dir="rtl"><header className="sticky top-0 z-10 bg-zinc-950/95 backdrop-blur border-b border-white/10 p-4 flex justify-between"><button onClick={onBack}><ArrowRight/></button><b>لوحة ZEVORA الإدارية</b><button onClick={load}><RefreshCw className="w-5 h-5"/></button></header><div className="max-w-5xl mx-auto p-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['المستخدمون',data?.usersTotal,Users],['الفيديوهات',data?.videosTotal,Video],['البلاغات المعلقة',data?.reportsPending,Flag],['الجلسات النشطة',data?.sessionsActive,ShieldCheck]].map(([t,v,I]:any)=><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><I className="w-5 h-5 text-cyan-400"/><b className="block text-2xl mt-3">{v??'—'}</b><span className="text-xs text-zinc-500">{t}</span></div>)}</div><section className="mt-6 rounded-2xl border border-white/10 overflow-hidden"><div className="p-4 border-b border-white/10 font-bold">المستخدمون المسجلون</div>{users.length===0?<div className="p-8 text-center text-zinc-500">لا توجد بيانات مستخدمين.</div>:users.map(u=><div key={u.id} className="p-4 border-b border-white/5 flex items-center justify-between gap-3"><div><b>{u.profile?.displayName||u.username}</b><div className="text-xs text-zinc-500">@{u.username} · {u.primaryProvider} · {u.status}</div></div><div className="flex gap-2"><button onClick={async()=>{await fetch(`/api/v1/admin/users/${u.id}/status`,{method:'POST',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({status:u.status==='BANNED'?'ACTIVE':'BANNED'})});load();}} className="px-3 py-2 rounded-lg bg-red-950/40 border border-red-800/40 text-xs text-red-300">{u.status==='BANNED'?'إلغاء الحظر':'حظر'}</button></div></div>)}</section>

<section className="mt-6 rounded-2xl border border-white/10 overflow-hidden"><div className="p-4 border-b border-white/10 font-bold">البلاغات الحقيقية</div>{reports.length===0?<div className="p-8 text-center text-zinc-500">لا توجد بلاغات حالية أو لم يرجع الخادم بيانات.</div>:reports.map(r=><div key={r.id} className="p-4 border-b border-white/5"><b>{r.reason}</b><div className="text-xs text-zinc-500 mt-1">{r.status} · {r.createdAt}</div></div>)}</section></div></div>;
};

===== END ZEVORA_BUNDLE_FILE =====
